#CRIAR LISAT
dados=(10,20,30,40,50)
#converter a para lista
lista_dados= list(dados)
#mais listas
lista_dados.append(60)
lista_dados.append(70)
#remover lista
lista_dados.pop(0)
#colocar primeiro dado
print('primeiro dados da lista:', lista_dados[0])
print('quantidade de dados lista:',len(lista_dados))
pessoa= {'nome':'uarley ', 'idade': 28 , 'profissão': 'analista'}
#agora colocar oq aparecer  no tela
print('nome:',pessoa['nome'])
       

